<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_admission</name>
   <tag></tag>
   <elementGuidId>9c8af743-7598-4481-a470-4ee1ac96d896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;chk_hospotal_readmission&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;chk_hospotal_readmission&quot;]</value>
      <webElementGuid>fe66876b-edd9-4cfc-ba63-cceb62677951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4e50e8a6-8c16-4930-8d67-9b98d61fd463</webElementGuid>
   </webElementProperties>
</WebElementEntity>
